host: localhost:8000
info:
  contact: {}
  description: alm-api server swagger docs
  title: alm-api
  version: "1.0"
paths:
  /auth/change-password:
    patch:
      produces:
      - application/json
      responses:
        "200":
          description: Successful Response
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      tags:
      - auth
  /auth/forgot-password:
    post:
      parameters:
      - description: registered email
        in: formData
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful Response
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      tags:
      - auth
  /auth/logout:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: Successful Response
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      tags:
      - auth
  /auth/refresh-token:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: Successful Response
          schema:
            type: string
      tags:
      - auth
  /auth/reset-password/{ptoken}:
    patch:
      parameters:
      - in: formData
        name: email
        required: true
        type: string
      - in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful Response
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      tags:
      - auth
  /auth/signup:
    post:
      parameters:
      - in: formData
        name: email
        required: true
        type: string
      - in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful Response
          schema:
            type: string
      tags:
      - auth
  /auth/token:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - in: formData
        name: email
        required: true
        type: string
      - in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful Response
          schema:
            type: string
      tags:
      - auth
  /auth/verify-email/{uid}:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: Successful Response
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
